"""
Global normalization statistics for ranker components.
Generated by evaluation/compute_norm_stats.py
"""
import json
import os

with open(os.path.join(os.path.dirname(__file__), 'normalization_stats.json'), 'r') as f:
    NORM_STATS = json.load(f)